### ISSUE TITLE
json-server

### ISSUE THREAD

**Issue by gadielkalleb** [gabrielrufino/minhas-series#1]
**json-server Como devDependencies**

Gabriel não seria interessante já incluir o json-server como devDepencies no packge.json do projeto ?

fiz o clone e qdo jaço o start do projeto e do json-server ele não encontra o mesmo pois não esta como dependencia do projeto. aqui na maquina eu coloquei como dependencia e usei seu script "server" para startar o mesmo.

**Comment by gabrielrufino** [comment]
Valeu pela dica, mano!! Demorou, mas resolvi hahaha Tô tentando voltar à ativa no github
